// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Comment struct {
	ID        string `json:"id"`
	PostID    string `json:"postID"`
	Content   string `json:"content"`
	AuthorID  string `json:"authorID"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	AuthorID  string     `json:"authorID"`
	Comments  []*Comment `json:"comments,omitempty"`
	CreatedAt string     `json:"createdAt"`
}

type Query struct {
}
